package com.example.emojibrite;




public class Users {

    private String HomePage;
    private String name;
    private String ImagePath;
    private String email;
    private String number;
    private String role;

    //fid is a unique id autogenerated by firebase each time
    //an instance of a firebase app is installed. this id gets deleted after
    //the app is uninstalled, cache is deleted or factory reset.
    //this id is used to identify the user in the database
    //what this means is for a new user, the FID is retrived. For old users, the FID is retrieved and compared to see if it is in the database
    //IF  the user is in the database, their profile is brought up
    private String uid;


    // unique id? add getter and setter

    // set to false by default in constructors
    private boolean enableNotification;

    private boolean enableGeolocationTracking;
//    private boolean isAdmin;
    /**
     * Users constructor with name, email, link to ImagePath  which can be
     * generated picture or the picture from the gallery,
     * and number
     * @param name of the user
     * @param email of the user
     * @param ImagePath of the picture
     */


    public Users(String uid, String name, String email, String HomePage, String ImagePath, String number) {
        this.uid = uid;
        this.name = name;
        this.email = email;
        this.HomePage = HomePage;
        this.ImagePath = ImagePath;
        this.number = number;
        this.enableNotification = false;
        this.enableGeolocationTracking = false;


    }
    public Users(String uid){
        this.uid = uid;
        this.name = null;
        this.email = null;
        this.ImagePath = null;
        this.number = null;
        this.enableNotification = false;
        this.enableGeolocationTracking = false;

    }
    /**
     * Users constructor with name and the link to ImagePath which cam be
     * generated picture or the picture from the gallery
     * @param name of the user
     * @param ImagePath of the picture
     */
    public Users(String name, String ImagePath) {
        this.name = name;
        this.ImagePath = ImagePath;
        this.enableNotification = false;
        this.enableGeolocationTracking = false;
    }


    public String getProfileUid() {
        return uid;
    }
    //no setter yet

    /**
     * Gets the name of the user
     * @return name of the user
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the user
     * @param name of the user
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the email of the user
     * @return email of the user
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email of the user
     * @param email of the user
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the HomePage of the user
     * @return HomePage of the user
     */
    public String getHomePage(){
        return HomePage;
    }


    /**
     * Gets the HomePage of the user
     * @param HomePage of the user
     */
    public void setHomePage(String HomePage){
        this.HomePage = HomePage;
    }


    /**
     * Gets the ImagePath of the user
     * @return ImagePath of the user
     */
    public String getImagePath() {
        return ImagePath;
    }

    /**
     * Sets the ImagePath of the user
     * @param imagePath of the user
     */
    public void setImagePath(String imagePath) {
        ImagePath = imagePath;
    }

    /**
     * Gets the number of the user
     * @return the number of the user
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the number of the user
     * @param number of the user
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * Gets the enableNotification of the user
     * @return the enableNotification of the user
     */
    public boolean isEnableNotification() {
        return enableNotification;
    }

    /**
     * Sets the enableNotification of the user
     * @param enableNotification of the user
     */
    public void setEnableNotification(boolean enableNotification) {
        this.enableNotification = enableNotification;
    }

    /**
     * Gets the enableGeolocationTracking of the user
     * @return the enableGeolocationTracking of the user
     */
    public boolean isEnableGeolocationTracking() {
        return enableGeolocationTracking;
    }

    /**
     * Sets the enableGeolocationTracking of the user
     * @param enableGeolocationTracking of the user
     */
    public void setEnableGeolocationTracking(boolean enableGeolocationTracking) {
        this.enableGeolocationTracking = enableGeolocationTracking;
    }

    /**
     * Gets the role of the user
     * @param role of the user
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Sets the role of the user
     * @return role of the user
     */
    public String getRole() {
        return role;
    }
}
