name: Android CI

on:
  push:
    branches: [ "main", "development","QRcode", "Aivan" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # might have to set up android sdk?
    # like name: "" uses: android-actions/setup-android@v3
    
    - name: Grant execute permission for gradlew
      working-directory: ./code
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./code
      run: ./gradlew build
